resourcepackapi:
  default_pack_name: pack.zip
  dropbox:
    enabled: false
    folder_path:
    access_token:
    resource_pack:
      url:
  local:
    folder_path:
    enabled: false
    resource_pack:
      url:
  ftp:
    enabled: false
    hostname:
    server_path:
    resource_pack:
      url:
    auth:
      username:
      password:
  sftp:
    enabled: false
    hostname:
    server_path:
    resource_pack:
      url:
    auth:
      keyBasedAuthentication: false
      username:
      password:
      key_file:
